export const EMPLOYEES=[{
    "id": 1,
    "name": "Jarrid",
    "email": "jscinelli0@diigo.com",
    "gender": "Female",
    "dob": "5/11/1981"
  }, {
    "id": 2,
    "name": "Eddie",
    "email": "ejakeway1@upenn.edu",
    "gender": "Female",
    "dob": "9/13/1967"
  }, {
    "id": 3,
    "name": "Darcey",
    "email": "ddantonio2@bbb.org",
    "gender": "Female",
    "dob": "4/1/1989"
  }, {
    "id": 4,
    "name": "Moyra",
    "email": "mbarnish3@stanford.edu",
    "gender": "Female",
    "dob": "2/26/1977"
  }, {
    "id": 5,
    "name": "Granthem",
    "email": "ghuddleston4@tmall.com",
    "gender": "Male",
    "dob": "2/27/1993"
  }, {
    "id": 6,
    "name": "Analiese",
    "email": "aobradain5@cloudflare.com",
    "gender": "Female",
    "dob": "9/15/1990"
  }, {
    "id": 7,
    "name": "Terence",
    "email": "tfosdick6@plala.or.jp",
    "gender": "Female",
    "dob": "11/7/1988"
  }, {
    "id": 8,
    "name": "Bessie",
    "email": "bbenois7@toplist.cz",
    "gender": "Female",
    "dob": "12/3/1961"
  }, {
    "id": 9,
    "name": "Janette",
    "email": "jflight8@skyrock.com",
    "gender": "Male",
    "dob": "12/2/1979"
  }, {
    "id": 10,
    "name": "Aryn",
    "email": "amennear9@soup.io",
    "gender": "Female",
    "dob": "10/30/1986"
  }, {
    "id": 11,
    "name": "Elaina",
    "email": "emcniffa@tamu.edu",
    "gender": "Male",
    "dob": "10/15/1980"
  }, {
    "id": 12,
    "name": "Chelsea",
    "email": "czanettib@globo.com",
    "gender": "Male",
    "dob": "10/15/1966"
  }, {
    "id": 13,
    "name": "Karlis",
    "email": "kvashchenkoc@loc.gov",
    "gender": "Female",
    "dob": "5/18/1998"
  }, {
    "id": 14,
    "name": "Guillemette",
    "email": "gtregidgad@mac.com",
    "gender": "Female",
    "dob": "3/9/1982"
  }, {
    "id": 15,
    "name": "Idelle",
    "email": "igente@marriott.com",
    "gender": "Male",
    "dob": "3/8/1986"
  }, {
    "id": 16,
    "name": "Oby",
    "email": "osimoensf@narod.ru",
    "gender": "Female",
    "dob": "12/30/1987"
  }, {
    "id": 17,
    "name": "Sauncho",
    "email": "skerssg@multiply.com",
    "gender": "Male",
    "dob": "12/6/1969"
  }, {
    "id": 18,
    "name": "Rossy",
    "email": "rlacknorh@homestead.com",
    "gender": "Male",
    "dob": "6/4/1977"
  }, {
    "id": 19,
    "name": "Kati",
    "email": "kfalconeri@nature.com",
    "gender": "Male",
    "dob": "3/27/1983"
  }, {
    "id": 20,
    "name": "Jenni",
    "email": "jcancellarioj@diigo.com",
    "gender": "Female",
    "dob": "8/9/1997"
  }]